remote_theme: pmarsceill/just-the-docs
repository: anonymous-review-submission/goalexplorer.git
search_enabled: true
aux_links:
    "Download GoalExplorer":
      - "https://drive.google.com/open?id=1w6MXs5gPbX-lpl2SE1jYz_Xo1A40rY13"
